<?php
namespace Tidor\FakerChilean\Provider;

use Faker\Provider\Base AS ProviderBase;

/**'
 * Product names
 */
class Product extends ProviderBase
{
    protected static $names = [
        'Aceite',
        'Aceite de oliva',
        'Agua con gas',
        'Agua sin gas',
        'Ajonjolí',
        'Almeja',
        'Arroz',
        'Atún',
        'Avena',
        'Azúcar',
        'Bacalao',
        'Bebida hidratante',
        'Blanco Nilo',
        'Bolillo',
        'Boquerón',
        'Cabeza de cerdo',
        'Café',
        'Cajeta',
        'Calamar',
        'Camarón',
        'Canela',
        'Carpa',
        'Cazón',
        'Cerdo',
        'Cereales',
        'Cereal mixto',
        'Cerveza',
        'Charal',
        'Chile',
        'Chile seco',
        'Chilorio',
        'Chocolate',
        'Flan',
        'Frijol',
        'Galletas',
        'Gelatina en polvo',
        'Gurrubata',
        'Haba',
        'Harina de arroz',
        'Harina de trigo',
        'Hojas de perejil',
        'Huachinango',
        'Jaiba',
        'Jugo de fruta',
        'Langosta',
        'Langostino',
        'Lenguado',
        'Lenteja',
        'Lisa',
        'Lobina',
        'Lomo de cerdo',
        'Manteca',
        'Margarina',
        'Mayonesa',
        'Miel de abeja',
        'Mostaza',
        'Pan',
        'Pavo',
        'Pechuga de pollo',
        'Peladillas',
        'Pescado seco salado',
        'Pimienta',
        'Pollo',
        'Pulpo',
        'Refresco',
        'Robalo',
        'Sal',
        'Salmón',
        'Salsa',
        'Sardina',
        'Sidra',
        'Sierra',
        'Te',
        'Ternera',
        'Torta Imperial',
        'Tortilla de harina de trigo',
        'Trucha',
        'Turrón',
        'Vainilla',
        'Vinagre',
        'Vino',
    ];

    public function productName()
    {
        return static::randomElement(static::$names);
    }
}
